name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - development
    tags:
      - v*
      - rc-*
  pull_request:
    branches:
      - main
      - development

jobs:
  setup:
    runs-on: alpine

    outputs:
      lowercase: ${{ steps.lowercase.outputs.LOWERCASE }}
      is_pr: ${{ steps.pr.outputs.IS_PR }}
      tag_name: ${{ steps.tag.outputs.TAG_NAME }}

    steps:
      - name: Convert repository owner to lowercase
        id: owner
        run: echo "LOWERCASE=$(echo ${{ forgejo.repository_owner }} | awk '{print tolower($0)}')" >> $FORGEJO_OUTPUT

      - name: Convert repository name to lowercase
        id: repository
        run: echo "LOWERCASE=$(echo ${{ forgejo.repository }} | awk '{print tolower($0)}')" >> $FORGEJO_OUTPUT

      - name: Check if currently in a pull request
        id: pr
        run: echo "IS_PR=$(test -n "${{ forgejo.event.pull_request }}" && echo "true" || echo "false")" >> $FORGEJO_OUTPUT

      - name: Create the tag name
        id: tag
        run: |
          if [[ "${{ forgejo.ref_type }}" == "tag" ]]; then
            echo "TAG_NAME=$(echo ${{ forgejo.ref_name }} | sed 's/^v//')" >> $FORGEJO_OUTPUT
          elif [[ "${{ forgejo.ref_name }}" == "main" ]]; then
            echo "TAG_NAME=latest" >> $FORGEJO_OUTPUT
          else
            if [[ "${{ steps.pr.outputs.IS_PR }}" == "true" ]]; then
              echo "TAG_NAME=pr-${{ forgejo.event.pull_request.number }}" >> $FORGEJO_OUTPUT
            else
              echo "TAG_NAME=${{ forgejo.ref_name }}" >> $FORGEJO_OUTPUT
            fi
          fi

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint

  build-and-push:
    runs-on: ubuntu-latest
    needs: [setup, lint]
    if: ${{ needs.setup.outputs.is_pr == 'false' }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Forgejo Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ forgejo.server_url }}
          username: ${{ forgejo.actor }}
          password: ${{ forgejo.token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          provenance: mode=max
          sbom: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ needs.setup.outputs.repository }}:${{ needs.setup.outputs.tag_name }}
            ${{ forgejo.server_url }}/${{ needs.setup.outputs.repository }}:${{ needs.setup.outputs.tag_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
